#!/bin/bash
set -e

module=$(git remote get-url ssh | sed 's/.*\///' | sed 's/\.git//')
v=$(s3d-flow-json | jq -r .latest)

s3d-push-down() {
  sed -i "s/$module?ref=.*\"/$module?ref=$v\"/" *.tf
  s3d-push
}

(cd ../aws-site && s3d-push-down)
